project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
  resources:
    - "class/"
    - "content/"
    - "rubrics/"
    - "slides/"
    - "data/"
    - "templates/"

website:
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: "Home"
        href: index.html
      - text: "Syllabus"
        icon: fa fa-map
        href: syllabus.html
      - text: "Schedule"
        icon: fa fa-calendar-alt
        href: schedule.html
      - section: "Class"
        contents:
          - index.qmd
      - section: "Assignments"
        contents:
          - layout.qmd
      - section: "Readings"
        contents:
          - layout.qmd
      - section: "References"
        contents:
          - layout.qmd
      - section: "Help"
        contents:
          - layout.qmd
      - section: "About"
        contents:
          - text: "About"
            icon: fa fa-info-circle
            href: about.html
          - text: "License"
            icon: fa fa-gavel
            href: LICENSE.html
          - text: "Contact"
            icon: fa fa-envelope
            href: mailto:jph@gwu.edu
          - text: "Source files"
            icon: fa fa-github
            href: https://github.com/emse-p4a-gwu/2022-Spring/
      
  page-footer:
    center:
      - text: '© 2022 John Paul Helveston <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> {{< var weekday >}} | <i class="far fa-clock"></i> {{< var time >}} | <a href="{{< var room_url >}}"><i class="fa fa-map-marker-alt"></i> {{< var room >}}</a> | <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:{{< var email >}}"><i class="fas fa-envelope"></i> {{< var email >}}</a> | <a href="{{< var repo >}}"><i class="fab fa-github"></i></a>'

format:
  html:
    theme: cosmo
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header: "_includes/header.html"

