project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
  resources:
    - "class/"
    - "rubrics/"
    - "slides/"
    - "data/"

website:
  title: EMSE 4571 / 6571
  image: images/logo.png
  site-url: https://p4a.seas.gwu.edu/2023-Spring/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-p4a-gwu/2023-Spring
  repo-actions: [edit, issue]
  description: 'Course website for Spring 2023 semester of the EMSE course "Intro. to Programming for Analytics" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://p4a.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Syllabus
        icon: map-fill
        href: syllabus.qmd
      - text: Schedule
        icon: table
        href: schedule.qmd
      - text: Textbook
        icon: book-fill
        href: https://p4a.jhelvy.com/
      - text: Software
        icon: download
        href: software.qmd
      - text: References
        icon: bookmark-fill
        href: references.qmd
      - text: Autograder
        icon: list-check
        href: autograder.html
      - text: Slack
        icon: slack
        href: https://emse-p4a-s23.slack.com
      - text: "Schedule a call w/Prof. Helveston"
        icon: clock-fill
        href: https://jhelvy.appointlet.com/b/professor-helveston
      - section: Other
        icon: question-circle-fill
        contents:
          - text: About
            icon: question-circle-fill
            href: about.qmd
          - text: License
            icon: award-fill
            href: LICENSE.qmd
          - text: Contact
            icon: envelope-fill
            href: mailto:jph@gwu.edu
          - text: Source files
            icon: github
            href: https://github.com/emse-p4a-gwu/2023-Spring
  page-footer:
    center:
      - text: '© 2023 John Paul Helveston <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> {{< var weekday >}} | <i class="far fa-clock"></i> {{< var time >}} | <a href="{{< var room_url >}}"><i class="fa fa-map-marker-alt"></i> {{< var room >}}</a> | <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:{{< var email >}}"><i class="fas fa-envelope"></i> {{< var email >}}</a> | <a href="{{< var repo >}}"><i class="fab fa-github"></i></a>'

format:
  html:
    theme: cosmo
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

filters:
    - schedule.lua
