# Schedule

All assignments are due by 11:59pm on the due date.

```{r}
#| echo: false
source("_common.R")
```

```{r}
#| echo: false
#| warning: false 
#| message: false

# NOTE: The schedule.lua file is inserted as a filter in _quarto.yml to 
# avoid the insertion of a <colgroup> in the html around this table: 
# https://github.com/jgm/pandoc/issues/8139

library(tidyverse)
library(kableExtra)

schedule <- get_schedule()

# Make the final schedule
names(schedule) <- str_to_title(names(schedule))
done <- schedule %>%
  select(Week, Date = Date_md, Quiz, Class, Assignments, Readings) %>% 
  kable(
    format = 'html',
    escape = FALSE,
    align = c('c', 'c', 'l', 'l', 'l', 'l')
  ) %>% 
  kable_styling(full_width = FALSE) %>% 
  column_spec(column = 1, width = '2em') %>%
  column_spec(column = 2, width = '3em') %>%
  column_spec(column = 4, width = '16em') %>% 
  column_spec(column = 5, width = '15em')

# # Add highlighting based on current week if we're still in the semester
# highlight <- which(Sys.Date() > (schedule$Date))
# if (Sys.Date() <= ymd("2023-05-12")) {
#   done <- done %>%
#     row_spec(highlight, background = "#C6C6C6")
# }

done
```
