```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)

source(here::here('_common.R'))

schedule <- get_schedule()

due <- schedule %>%
    filter(n_assign == params$number) %>% 
    mutate(due_assign = format(due_assign, format = "%b %d")) %>%
    pull(due_assign) %>%
    paste0(" by 11:59pm")

readings_current <- schedule %>%
    filter(n_assign == params$number) %>% 
    pull(readings)

readings_next <- schedule %>% 
    filter(n_assign == (params$number + 1)) %>% 
    pull(readings)

url_template <- paste0(
  'https://p4a.seas.gwu.edu/2023-Spring/templates/hw',
  params$number, '.zip')
```

> **Due**: `r due`
>
> **Submission Instructions**: Create a zip file of all the files in your R project folder for this assignment, then submit your zip file on the corresponding assignment submission on Blackboard.
>
> **Weight**: This assignment is worth 4% of your final grade.
>
> **Purpose**: `r params$purpose`
>
> **Assessment**: Each question indicates the % of the assignment grade, summing to 100%. The credit for each question will be assigned as follows:
>
> - 0% for not attempting a response.
> - 50% for attempting the question but with _major_ errors.
> - 75% for attempting the question but with _minor_ errors.
> - 100% for correctly answering the question.
>
> The reflection portion is always worth 10% and graded for completion.
>
> **Rules**:
>
> - Problems marked **SOLO** may not be worked on with other classmates, though you may consult instructors for help.
> - For problems marked **COLLABORATIVE**, you may work in groups of up to 3 students who are in this course this semester. You may not split up the work -- everyone must work on every problem. And you may not simply copy any code but rather truly work together and submit your own solutions.

